import { EmptyArray, TreeTypes } from './constants';

export default {
  alignLabels: false,
  branchScale: null,
  collapsedIds: EmptyArray,
  fillStyle: '#222',
  fontFamily: 'serif',
  fontSize: 16,
  fontWeight: 'normal',
  haloRadius: 12,
  haloStyle: '#3C7383',
  haloWidth: 4,
  highlightedId: null,
  highlightedStyle: '#3C7383',
  internalNodeStyle: { shape: 'none' },
  labelThreshold: 8,
  leafNodeStyle: { shape: 'circle' },
  lineWidth: 1,
  nodeSize: 14,
  nodesPowRatio: 0.5,
  padding: 32,
  renderInternalLabels: false,
  renderLabels: true,
  renderLeafLabels: true,
  rootId: null,
  rotatedIds: EmptyArray,
  selectableInternalNodes: true,
  selectableLeafNodes: true,
  selectedIds: EmptyArray,
  showLabels: false,
  showNodes: true,
  stepScale: 8,
  strokeStyle: '#222',
  styleLeafLabels: false,
  styleNodeLines: false,
  styles: {},
  type: TreeTypes.Rectangular,
  zoomFactor: 3,
};
